Config:
    enter-message: true
    enter-message-text: "&6&lWelcome to the server %player%! &f| &5TSetSpawn"
    go-spawn: true
    join: true
    join-message: "&5TSetSpawn &e> &f%player% has joined."
    quit: true
    quit-message: "&5TSetSpawn &e> &f%player% has left."
    welcome: true
    welcome-message: "&5TSetSpawn &e> &f%player% entered for the first time!"
    cooldown-time: 5
    wait-time: 5
    enable-first-time-teleport: true
    enable-void-teleport: true
    Translate:
      version: "&5TSetSpawn &e> &7The version is: %version%"
      spawn-not-placed: "&5TSetSpawn &e> &cThe spawn does not exist"
      console: "&5TSetSpawn &e> &7You cannot send commands from the console"
      spawn-placed: "&5TSetSpawn &e> &aSpawn placed"
      reload: "&5TSetSpawn &e> &aReloaded"
      unknown-command: "&5TSetSpawn &e> &cUnknown command"
      help: "&5TSetSpawn &e> &fUse the command &a/spawn &fto go to the spawn"
      spawn: "&5TSetSpawn &e> &fYou have been teleported"
      no-permission: "&5TSetSpawn &e> &cYou do not have permissions"
      cooldown-message: "&5TSetSpawn &e> &cYou have to wait &e%time% &cseconds before running this command again!"
      wait-time-message: "&5TSetSpawn &e> &fTeleporting..."
      first-time-teleport: "&5TSetSpawn &e> &fWelcome to the server %player%!"
      void-teleport-message: "&5TSetSpawn &e> &fTeleported to the Spawn"
    Particles:
      enabled: true
      radius: 1.5
      amount: 50
      particle-type: MOBSPAWNER_FLAMES