main: minealex.tsetspawn.TSetSpawn
version: 1.6
name: TSetSpawn

commands:
  tsetspawn:
    description: Help command
  spawn:
    description: Go to the spawn
  setspawn:
    description: Set the spawn