name: TSetSpawn
version: 4.0.0
main: tsetspawn.TSetSpawn

author: Mine_Alex | Tect.host
api-version: '1.13'
website: tect.host

commands:
  tsetspawn:
    usage: /tss <command>
    aliases:
      - tss
  setspawn:
    usage: /setspawn <id>
  spawn:
    usage: /spawn